"""Shared report-schema names used by report analysis helpers.

These constants are not an alternate schema catalog. They are the small set of
table/column names that runtime code uses in multiple places. Keeping them here
prevents drift between context, capability detection, facts, and doctor checks.
"""

from __future__ import annotations

TABLE_CUDA_KERNEL = "CUPTI_ACTIVITY_KIND_KERNEL"
TABLE_CUDA_RUNTIME = "CUPTI_ACTIVITY_KIND_RUNTIME"
TABLE_CUDA_MEMCPY = "CUPTI_ACTIVITY_KIND_MEMCPY"
TABLE_CUDA_MEMSET = "CUPTI_ACTIVITY_KIND_MEMSET"
TABLE_CUDA_SYNC = "CUPTI_ACTIVITY_KIND_SYNCHRONIZATION"
TABLE_CUDA_GRAPH_TRACE = "CUPTI_ACTIVITY_KIND_GRAPH_TRACE"
TABLE_CUDA_GRAPH_NODE_EVENTS = "CUDA_GRAPH_NODE_EVENTS"
TABLE_CUDA_GRAPH_EVENTS = "CUDA_GRAPH_EVENTS"
TABLE_DIAGNOSTIC_EVENT = "DIAGNOSTIC_EVENT"
TABLE_ENUM_CUDA_MEMCPY_OPER = "ENUM_CUDA_MEMCPY_OPER"
TABLE_ENUM_CUDA_MEM_KIND = "ENUM_CUDA_MEM_KIND"
TABLE_GPU_METRICS = "GPU_METRICS"
TABLE_META_DATA_EXPORT = "META_DATA_EXPORT"
TABLE_MPI_COLLECTIVES = "MPI_COLLECTIVES_EVENTS"
TABLE_NVTX_EVENTS = "NVTX_EVENTS"
TABLE_OSRT_API = "OSRT_API"
TABLE_STRING_IDS = "StringIds"
TABLE_TARGET_INFO_CUDA_DEVICE = "TARGET_INFO_CUDA_DEVICE"
TABLE_TARGET_INFO_GPU = "TARGET_INFO_GPU"
TABLE_TARGET_INFO_GPU_METRICS = "TARGET_INFO_GPU_METRICS"
TABLE_TARGET_INFO_PROCESS = "TARGET_INFO_PROCESS"
TABLE_TARGET_INFO_SESSION_START_TIME = "TARGET_INFO_SESSION_START_TIME"
TABLE_TARGET_INFO_SYSTEM_ENV = "TARGET_INFO_SYSTEM_ENV"
TABLE_SAMPLING_CALLCHAINS = "SAMPLING_CALLCHAINS"
TABLE_COMPOSITE_EVENTS = "COMPOSITE_EVENTS"
TABLE_SCHED_EVENTS = "SCHED_EVENTS"
TABLE_ENUM_SCHEDULING_THREAD_BLOCK = "ENUM_SCHEDULING_THREAD_BLOCK"
TABLE_THREAD_NAMES = "ThreadNames"
TABLE_DX12_API = "DX12_API"
TABLE_DX11_API = "DX11_API"
TABLE_DXGI_API = "DXGI_API"
TABLE_VULKAN_API = "VULKAN_API"
TABLE_OPENGL_API = "OPENGL_API"
TABLE_DX12_WORKLOAD = "DX12_WORKLOAD"
TABLE_VULKAN_WORKLOAD = "VULKAN_WORKLOAD"
TABLE_OPENGL_WORKLOAD = "OPENGL_WORKLOAD"
TABLE_ETW_EVENTS = "ETW_EVENTS"
TABLE_GENERIC_EVENT_TYPES = "GENERIC_EVENT_TYPES"
TABLE_WDDM_EVICT_ALLOCATION = "WDDM_EVICT_ALLOCATION_EVENTS"
TABLE_WDDM_PAGING_QUEUE_PACKET_INFO = "WDDM_PAGING_QUEUE_PACKET_INFO_EVENTS"
TABLE_WDDM_DMA_PACKET_START = "WDDM_DMA_PACKET_START_EVENTS"
TABLE_GPU_CONTEXT_SWITCH = "GPU_CONTEXT_SWITCH_EVENTS"
WDDM_TABLE_PREFIX = "WDDM_"
GRAPHICS_API_TABLES = frozenset(
    {
        TABLE_DX12_API,
        TABLE_DX11_API,
        TABLE_DXGI_API,
        TABLE_VULKAN_API,
        TABLE_OPENGL_API,
    }
)

GRAPHICS_API_WORKLOAD_PAIRS = (
    (TABLE_DX12_API, TABLE_DX12_WORKLOAD),
    (TABLE_VULKAN_API, TABLE_VULKAN_WORKLOAD),
    (TABLE_OPENGL_API, TABLE_OPENGL_WORKLOAD),
)

SYNTHETIC_REPORT_LABEL = "__report_label"
SYNTHETIC_REPORT_INDEX = "__report_index"
SYNTHETIC_REPORT_COLUMNS = (SYNTHETIC_REPORT_LABEL, SYNTHETIC_REPORT_INDEX)

CUDA_GRAPH_TABLES = frozenset(
    {
        TABLE_CUDA_GRAPH_TRACE,
        TABLE_CUDA_GRAPH_NODE_EVENTS,
        TABLE_CUDA_GRAPH_EVENTS,
    }
)

CPU_SAMPLING_TABLES = frozenset({TABLE_SAMPLING_CALLCHAINS, TABLE_COMPOSITE_EVENTS})

DOCUMENTED_SCHEMA_TABLES = frozenset(
    {
        TABLE_CUDA_KERNEL,
        TABLE_CUDA_RUNTIME,
        TABLE_CUDA_MEMCPY,
        TABLE_CUDA_MEMSET,
        TABLE_CUDA_SYNC,
        TABLE_DIAGNOSTIC_EVENT,
        TABLE_ENUM_CUDA_MEMCPY_OPER,
        TABLE_ENUM_CUDA_MEM_KIND,
        TABLE_GPU_METRICS,
        TABLE_META_DATA_EXPORT,
        TABLE_MPI_COLLECTIVES,
        TABLE_NVTX_EVENTS,
        TABLE_OSRT_API,
        TABLE_STRING_IDS,
        TABLE_TARGET_INFO_CUDA_DEVICE,
        TABLE_TARGET_INFO_GPU,
        TABLE_TARGET_INFO_GPU_METRICS,
        TABLE_TARGET_INFO_PROCESS,
        TABLE_TARGET_INFO_SESSION_START_TIME,
        TABLE_TARGET_INFO_SYSTEM_ENV,
        TABLE_DXGI_API,
        TABLE_DX12_API,
        TABLE_DX12_WORKLOAD,
        TABLE_VULKAN_API,
        TABLE_VULKAN_WORKLOAD,
        TABLE_OPENGL_API,
        TABLE_OPENGL_WORKLOAD,
        TABLE_ETW_EVENTS,
        TABLE_GENERIC_EVENT_TYPES,
        TABLE_WDDM_EVICT_ALLOCATION,
        TABLE_WDDM_PAGING_QUEUE_PACKET_INFO,
        TABLE_WDDM_DMA_PACKET_START,
        TABLE_GPU_CONTEXT_SWITCH,
        TABLE_SCHED_EVENTS,
        TABLE_ENUM_SCHEDULING_THREAD_BLOCK,
        TABLE_THREAD_NAMES,
        *CUDA_GRAPH_TABLES,
        *CPU_SAMPLING_TABLES,
    }
)

INTERESTING_TABLE_KEYWORDS = (
    "KERNEL",
    "RUNTIME",
    "NVTX",
    "MEMCPY",
    "MPI",
    "NCCL",
    "DIAGNOSTIC",
)

# Keep automatic context useful without exposing host identifiers. Hostname is
# intentionally omitted; users can query it explicitly if local policy allows.
SYSTEM_ENV_CONTEXT_FIELDS = (
    "CpuCores",
    "CpuSpeedMhz",
    "CpuArchitecture",
    "OS",
    "LinuxKernelVersion",
    "DeviceVendor",
)

NCCL_TABLE_PATTERN = ".*NCCL.*"


def upper_table_names(tables: set[str] | list[str] | tuple[str, ...]) -> set[str]:
    return {table.upper() for table in tables}


def interesting_tables(tables: list[str] | set[str], *, limit: int = 60) -> list[str]:
    """Return table names worth surfacing in context payloads."""

    return [
        table
        for table in sorted(tables)
        if any(keyword in table.upper() for keyword in INTERESTING_TABLE_KEYWORDS)
    ][:limit]
